"""migracionn

Revision ID: 638687fc03ef
Revises: c4211f3ed78d
Create Date: 2025-04-22 14:01:18.294620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638687fc03ef'
down_revision = 'c4211f3ed78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombreEmpresa', sa.String(length=100), nullable=False))
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('nombreEmpresa')

    # ### end Alembic commands ###
