"""agregar descripcion y rubro a empresas

Revision ID: 6c11b863639e
Revises: d4c2ae0ea78b
Create Date: 2025-04-23 11:55:18.742013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c11b863639e'
down_revision = 'd4c2ae0ea78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actividad', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('actividad')

    # ### end Alembic commands ###
