"""migracionn

Revision ID: c4211f3ed78d
Revises: c4e1d178569d
Create Date: 2025-04-22 02:13:29.697587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4211f3ed78d'
down_revision = 'c4e1d178569d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.alter_column('N_telefono',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.alter_column('N_telefono',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
