"""agregar descripcion y rubro a empresas

Revision ID: c8b31ccdf028
Revises: fb958f1c8c20
Create Date: 2025-04-23 18:49:56.933595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b31ccdf028'
down_revision = 'fb958f1c8c20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitud_longitud', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('microempresario', schema=None) as batch_op:
        batch_op.drop_column('latitud_longitud')

    # ### end Alembic commands ###
