"""migracionn

Revision ID: d4c2ae0ea78b
Revises: 
Create Date: 2025-04-23 00:22:39.731169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c2ae0ea78b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresa', sa.String(length=100), nullable=False),
    sa.Column('tipo_empresa', sa.String(length=100), nullable=False),
    sa.Column('nivel_madurez', sa.String(length=100), nullable=False),
    sa.Column('n_empleados', sa.Integer(), nullable=False),
    sa.Column('negocio_familiar', sa.Boolean(), nullable=False),
    sa.Column('ingresos_semanales', sa.Integer(), nullable=False),
    sa.Column('antiguedad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('microempresario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_empresario', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=100), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('n_telefono', sa.String(length=100), nullable=False),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('Webinars', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('nivel_educativo', sa.String(length=100), nullable=False),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaborador.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CursosTerminados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('microempresario_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['Cursos.id'], ),
    sa.ForeignKeyConstraint(['microempresario_id'], ['microempresario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CursosTerminados')
    op.drop_table('microempresario')
    op.drop_table('empresas')
    # ### end Alembic commands ###
