"""agregar descripcion y rubro a empresas

Revision ID: fb958f1c8c20
Revises: 6c11b863639e
Create Date: 2025-04-23 16:12:49.488094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb958f1c8c20'
down_revision = '6c11b863639e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zona', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('colaborador', schema=None) as batch_op:
        batch_op.drop_column('zona')

    # ### end Alembic commands ###
